Adauga case pentru argument invalid

diff --git a/myLast b/myLast
--- a/myLast
+++ b/myLast
@@ -19,6 +19,10 @@ while [[ $# -gt 0 ]]; do
             ARG_UNTIL="$2"
             shift 2
             ;;
+        *)
+            echo "Invalid argument: $1"
+            exit 1
+            ;;
     esac
 done
 
